# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.mqtt import MQTT
from swagger_server import util


class ChargerSoC(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, datalist: List[float]=None, mqtt: MQTT=None):  # noqa: E501
        """ChargerSoC - a model defined in Swagger

        :param datalist: The datalist of this ChargerSoC.  # noqa: E501
        :type datalist: List[float]
        :param mqtt: The mqtt of this ChargerSoC.  # noqa: E501
        :type mqtt: MQTT
        """
        self.swagger_types = {
            'datalist': List[float],
            'mqtt': MQTT
        }

        self.attribute_map = {
            'datalist': 'datalist',
            'mqtt': 'mqtt'
        }

        self._datalist = datalist
        self._mqtt = mqtt

    @classmethod
    def from_dict(cls, dikt) -> 'ChargerSoC':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The charger_SoC of this ChargerSoC.  # noqa: E501
        :rtype: ChargerSoC
        """
        return util.deserialize_model(dikt, cls)

    @property
    def datalist(self) -> List[float]:
        """Gets the datalist of this ChargerSoC.


        :return: The datalist of this ChargerSoC.
        :rtype: List[float]
        """
        return self._datalist

    @datalist.setter
    def datalist(self, datalist: List[float]):
        """Sets the datalist of this ChargerSoC.


        :param datalist: The datalist of this ChargerSoC.
        :type datalist: List[float]
        """

        self._datalist = datalist

    @property
    def mqtt(self) -> MQTT:
        """Gets the mqtt of this ChargerSoC.


        :return: The mqtt of this ChargerSoC.
        :rtype: MQTT
        """
        return self._mqtt

    @mqtt.setter
    def mqtt(self, mqtt: MQTT):
        """Sets the mqtt of this ChargerSoC.


        :param mqtt: The mqtt of this ChargerSoC.
        :type mqtt: MQTT
        """

        self._mqtt = mqtt
