# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401
from swagger_server.models.charger_recharge import ChargerRecharge  # noqa: F401,E501
from swagger_server.models.charger_so_c import ChargerSoC  # noqa: F401,E501

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Charger(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, max_charging_power_k_w: float=None, hosted_ev: str=None, so_c: ChargerSoC=None, recharge: ChargerRecharge=None):  # noqa: E501
        """Charger - a model defined in Swagger

        :param max_charging_power_k_w: The max_charging_power_k_w of this Charger.  # noqa: E501
        :type max_charging_power_k_w: float
        :param hosted_ev: The hosted_ev of this Charger.  # noqa: E501
        :type hosted_ev: str
        :param so_c: The so_c of this Charger.  # noqa: E501
        :type so_c: ChargerSoC
        :param recharge: The recharge of this Charger.  # noqa: E501
        :type recharge: ChargerRecharge
        """
        self.swagger_types = {
            'max_charging_power_k_w': float,
            'hosted_ev': str,
            'so_c': ChargerSoC,
            'recharge': ChargerRecharge
        }

        self.attribute_map = {
            'max_charging_power_k_w': 'Max_Charging_Power_kW',
            'hosted_ev': 'Hosted_EV',
            'so_c': 'SoC',
            'recharge': 'recharge'
        }

        self._max_charging_power_k_w = max_charging_power_k_w
        self._hosted_ev = hosted_ev
        self._so_c = so_c
        self._recharge = recharge

    @classmethod
    def from_dict(cls, dikt) -> 'Charger':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The charger of this Charger.  # noqa: E501
        :rtype: Charger
        """
        return util.deserialize_model(dikt, cls)

    @property
    def max_charging_power_k_w(self) -> float:
        """Gets the max_charging_power_k_w of this Charger.


        :return: The max_charging_power_k_w of this Charger.
        :rtype: float
        """
        return self._max_charging_power_k_w

    @max_charging_power_k_w.setter
    def max_charging_power_k_w(self, max_charging_power_k_w: float):
        """Sets the max_charging_power_k_w of this Charger.


        :param max_charging_power_k_w: The max_charging_power_k_w of this Charger.
        :type max_charging_power_k_w: float
        """

        self._max_charging_power_k_w = max_charging_power_k_w

    @property
    def hosted_ev(self) -> str:
        """Gets the hosted_ev of this Charger.


        :return: The hosted_ev of this Charger.
        :rtype: str
        """
        return self._hosted_ev

    @hosted_ev.setter
    def hosted_ev(self, hosted_ev: str):
        """Sets the hosted_ev of this Charger.


        :param hosted_ev: The hosted_ev of this Charger.
        :type hosted_ev: str
        """

        self._hosted_ev = hosted_ev

    @property
    def so_c(self) -> ChargerSoC:
        """Gets the so_c of this Charger.


        :return: The so_c of this Charger.
        :rtype: ChargerSoC
        """
        return self._so_c

    @so_c.setter
    def so_c(self, so_c: ChargerSoC):
        """Sets the so_c of this Charger.


        :param so_c: The so_c of this Charger.
        :type so_c: ChargerSoC
        """

        self._so_c = so_c

    @property
    def recharge(self) -> ChargerRecharge:
        """Gets the recharge of this Charger.


        :return: The recharge of this Charger.
        :rtype: ChargerRecharge
        """
        return self._recharge

    @recharge.setter
    def recharge(self, recharge: ChargerRecharge):
        """Sets the recharge of this Charger.


        :param recharge: The recharge of this Charger.
        :type recharge: ChargerRecharge
        """

        self._recharge = recharge
