# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.charger_mqtt import ChargerMqtt  # noqa: F401,E501
from swagger_server import util


class ChargersMqtt(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self):  # noqa: E501
        """ChargersMqtt - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'ChargersMqtt':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The chargers_mqtt of this ChargersMqtt.  # noqa: E501
        :rtype: ChargersMqtt
        """
        return util.deserialize_model(dikt, cls)
