# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.meta_ess import MetaESS  # noqa: F401,E501
from swagger_server.models.source_ess import SourceESS  # noqa: F401,E501
from swagger_server import util


class ESS(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, so_c_value: SourceESS=None, meta: MetaESS=None):  # noqa: E501
        """ESS - a model defined in Swagger

        :param so_c_value: The so_c_value of this ESS.  # noqa: E501
        :type so_c_value: SourceESS
        :param meta: The meta of this ESS.  # noqa: E501
        :type meta: MetaESS
        """
        self.swagger_types = {
            'so_c_value': SourceESS,
            'meta': MetaESS
        }

        self.attribute_map = {
            'so_c_value': 'SoC_Value',
            'meta': 'meta'
        }

        self._so_c_value = so_c_value
        self._meta = meta

    @classmethod
    def from_dict(cls, dikt) -> 'ESS':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ESS of this ESS.  # noqa: E501
        :rtype: ESS
        """
        return util.deserialize_model(dikt, cls)

    @property
    def so_c_value(self) -> SourceESS:
        """Gets the so_c_value of this ESS.


        :return: The so_c_value of this ESS.
        :rtype: SourceESS
        """
        return self._so_c_value

    @so_c_value.setter
    def so_c_value(self, so_c_value: SourceESS):
        """Sets the so_c_value of this ESS.


        :param so_c_value: The so_c_value of this ESS.
        :type so_c_value: SourceESS
        """
        if so_c_value is None:
            raise ValueError("Invalid value for `so_c_value`, must not be `None`")  # noqa: E501

        self._so_c_value = so_c_value

    @property
    def meta(self) -> MetaESS:
        """Gets the meta of this ESS.


        :return: The meta of this ESS.
        :rtype: MetaESS
        """
        return self._meta

    @meta.setter
    def meta(self, meta: MetaESS):
        """Sets the meta of this ESS.


        :param meta: The meta of this ESS.
        :type meta: MetaESS
        """

        self._meta = meta
