# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.meta_ess import MetaESS  # noqa: F401,E501
from swagger_server import util


class ESSFile(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self):  # noqa: E501
        """ESSFile - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'ESSFile':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ESS_File of this ESSFile.  # noqa: E501
        :rtype: ESSFile
        """
        return util.deserialize_model(dikt, cls)
