# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.ev import Ev  # noqa: F401,E501
from swagger_server.models.ev_meta import EvMeta  # noqa: F401,E501
from swagger_server import util


class EvFile(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, meta: EvMeta=None):  # noqa: E501
        """EvFile - a model defined in Swagger

        :param meta: The meta of this EvFile.  # noqa: E501
        :type meta: EvMeta
        """
        self.swagger_types = {
            'meta': EvMeta
        }

        self.attribute_map = {
            'meta': 'meta'
        }

        self._meta = meta

    @classmethod
    def from_dict(cls, dikt) -> 'EvFile':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ev_File of this EvFile.  # noqa: E501
        :rtype: EvFile
        """
        return util.deserialize_model(dikt, cls)

    @property
    def meta(self) -> EvMeta:
        """Gets the meta of this EvFile.


        :return: The meta of this EvFile.
        :rtype: EvMeta
        """
        return self._meta

    @meta.setter
    def meta(self, meta: EvMeta):
        """Sets the meta of this EvFile.


        :param meta: The meta of this EvFile.
        :type meta: EvMeta
        """

        self._meta = meta
