# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.ess_file import ESSFile  # noqa: F401,E501
from swagger_server.models.generic_file import GenericFile  # noqa: F401,E501
from swagger_server.models.global_control_file import GlobalControlFile  # noqa: F401,E501
from swagger_server.models.grid import Grid  # noqa: F401,E501
from swagger_server.models.load_file import LoadFile  # noqa: F401,E501
from swagger_server.models.pv_file import PVFile  # noqa: F401,E501
from swagger_server import util


class FileInputSource(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, generic: GenericFile=None, load: LoadFile=None, photovoltaic: PVFile=None, ess: ESSFile=None, grid: Grid=None, global_control: GlobalControlFile=None):  # noqa: E501
        """FileInputSource - a model defined in Swagger

        :param generic: The generic of this FileInputSource.  # noqa: E501
        :type generic: GenericFile
        :param load: The load of this FileInputSource.  # noqa: E501
        :type load: LoadFile
        :param photovoltaic: The photovoltaic of this FileInputSource.  # noqa: E501
        :type photovoltaic: PVFile
        :param ess: The ess of this FileInputSource.  # noqa: E501
        :type ess: ESSFile
        :param grid: The grid of this FileInputSource.  # noqa: E501
        :type grid: Grid
        :param global_control: The global_control of this FileInputSource.  # noqa: E501
        :type global_control: GlobalControlFile
        """
        self.swagger_types = {
            'generic': GenericFile,
            'load': LoadFile,
            'photovoltaic': PVFile,
            'ess': ESSFile,
            'grid': Grid,
            'global_control': GlobalControlFile
        }

        self.attribute_map = {
            'generic': 'generic',
            'load': 'load',
            'photovoltaic': 'photovoltaic',
            'ess': 'ESS',
            'grid': 'grid',
            'global_control': 'global_control'
        }

        self._generic = generic
        self._load = load
        self._photovoltaic = photovoltaic
        self._ess = ess
        self._grid = grid
        self._global_control = global_control

    @classmethod
    def from_dict(cls, dikt) -> 'FileInputSource':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FileInputSource of this FileInputSource.  # noqa: E501
        :rtype: FileInputSource
        """
        return util.deserialize_model(dikt, cls)

    @property
    def generic(self) -> GenericFile:
        """Gets the generic of this FileInputSource.


        :return: The generic of this FileInputSource.
        :rtype: GenericFile
        """
        return self._generic

    @generic.setter
    def generic(self, generic: GenericFile):
        """Sets the generic of this FileInputSource.


        :param generic: The generic of this FileInputSource.
        :type generic: GenericFile
        """

        self._generic = generic

    @property
    def load(self) -> LoadFile:
        """Gets the load of this FileInputSource.


        :return: The load of this FileInputSource.
        :rtype: LoadFile
        """
        return self._load

    @load.setter
    def load(self, load: LoadFile):
        """Sets the load of this FileInputSource.


        :param load: The load of this FileInputSource.
        :type load: LoadFile
        """

        self._load = load

    @property
    def photovoltaic(self) -> PVFile:
        """Gets the photovoltaic of this FileInputSource.


        :return: The photovoltaic of this FileInputSource.
        :rtype: PVFile
        """
        return self._photovoltaic

    @photovoltaic.setter
    def photovoltaic(self, photovoltaic: PVFile):
        """Sets the photovoltaic of this FileInputSource.


        :param photovoltaic: The photovoltaic of this FileInputSource.
        :type photovoltaic: PVFile
        """

        self._photovoltaic = photovoltaic

    @property
    def ess(self) -> ESSFile:
        """Gets the ess of this FileInputSource.


        :return: The ess of this FileInputSource.
        :rtype: ESSFile
        """
        return self._ess

    @ess.setter
    def ess(self, ess: ESSFile):
        """Sets the ess of this FileInputSource.


        :param ess: The ess of this FileInputSource.
        :type ess: ESSFile
        """

        self._ess = ess

    @property
    def grid(self) -> Grid:
        """Gets the grid of this FileInputSource.


        :return: The grid of this FileInputSource.
        :rtype: Grid
        """
        return self._grid

    @grid.setter
    def grid(self, grid: Grid):
        """Sets the grid of this FileInputSource.


        :param grid: The grid of this FileInputSource.
        :type grid: Grid
        """

        self._grid = grid

    @property
    def global_control(self) -> GlobalControlFile:
        """Gets the global_control of this FileInputSource.


        :return: The global_control of this FileInputSource.
        :rtype: GlobalControlFile
        """
        return self._global_control

    @global_control.setter
    def global_control(self, global_control: GlobalControlFile):
        """Sets the global_control of this FileInputSource.


        :param global_control: The global_control of this FileInputSource.
        :type global_control: GlobalControlFile
        """

        self._global_control = global_control
