# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.source_ess import SourceESS  # noqa: F401,E501
from swagger_server import util


class GenericMqttOutput(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, name: str=None, generic_name: SourceESS=None):  # noqa: E501
        """GenericMqttOutput - a model defined in Swagger

        :param name: The name of this GenericMqttOutput.  # noqa: E501
        :type name: str
        :param generic_name: The generic_name of this GenericMqttOutput.  # noqa: E501
        :type generic_name: SourceESS
        """
        self.swagger_types = {
            'name': str,
            'generic_name': SourceESS
        }

        self.attribute_map = {
            'name': 'name',
            'generic_name': 'generic_name'
        }

        self._name = name
        self._generic_name = generic_name

    @classmethod
    def from_dict(cls, dikt) -> 'GenericMqttOutput':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Generic_mqtt_Output of this GenericMqttOutput.  # noqa: E501
        :rtype: GenericMqttOutput
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this GenericMqttOutput.

        Name defining the parameter into the optimization model  # noqa: E501

        :return: The name of this GenericMqttOutput.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this GenericMqttOutput.

        Name defining the parameter into the optimization model  # noqa: E501

        :param name: The name of this GenericMqttOutput.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def generic_name(self) -> SourceESS:
        """Gets the generic_name of this GenericMqttOutput.


        :return: The generic_name of this GenericMqttOutput.
        :rtype: SourceESS
        """
        return self._generic_name

    @generic_name.setter
    def generic_name(self, generic_name: SourceESS):
        """Sets the generic_name of this GenericMqttOutput.


        :param generic_name: The generic_name of this GenericMqttOutput.
        :type generic_name: SourceESS
        """

        self._generic_name = generic_name
