# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class GenericFile(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, name: str=None, file: List[float]=None):  # noqa: E501
        """GenericFile - a model defined in Swagger

        :param name: The name of this GenericFile.  # noqa: E501
        :type name: str
        :param file: The file of this GenericFile.  # noqa: E501
        :type file: List[float]
        """
        self.swagger_types = {
            'name': str,
            'file': List[float]
        }

        self.attribute_map = {
            'name': 'name',
            'file': 'file'
        }

        self._name = name
        self._file = file

    @classmethod
    def from_dict(cls, dikt) -> 'GenericFile':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Generic_File of this GenericFile.  # noqa: E501
        :rtype: GenericFile
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this GenericFile.

        Name defining the parameter into the optimization model  # noqa: E501

        :return: The name of this GenericFile.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this GenericFile.

        Name defining the parameter into the optimization model  # noqa: E501

        :param name: The name of this GenericFile.
        :type name: str
        """

        self._name = name

    @property
    def file(self) -> List[float]:
        """Gets the file of this GenericFile.


        :return: The file of this GenericFile.
        :rtype: List[float]
        """
        return self._file

    @file.setter
    def file(self, file: List[float]):
        """Sets the file of this GenericFile.


        :param file: The file of this GenericFile.
        :type file: List[float]
        """
        if file is None:
            raise ValueError("Invalid value for `file`, must not be `None`")  # noqa: E501

        self._file = file
