# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.meta_gloabl_control import MetaGloablControl  # noqa: F401,E501

from swagger_server import util


class GlobalControlFile(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self):  # noqa: E501
        """GlobalControlFile - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'GlobalControlFile':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Global_Control_File of this GlobalControlFile.  # noqa: E501
        :rtype: GlobalControlFile
        """
        return util.deserialize_model(dikt, cls)
