# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.source import Source  # noqa: F401,E501
from swagger_server import util


class GridOutput(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, p_grid_export_output: Source=None, q_grid_export_output: Source=None, p_grid_import_output: Source=None, q_grid_import_output: Source=None):  # noqa: E501
        """GridOutput - a model defined in Swagger

        :param p_grid_export_output: The p_grid_export_output of this GridOutput.  # noqa: E501
        :type p_grid_export_output: Source
        :param q_grid_export_output: The q_grid_export_output of this GridOutput.  # noqa: E501
        :type q_grid_export_output: Source
        :param p_grid_import_output: The p_grid_import_output of this GridOutput.  # noqa: E501
        :type p_grid_import_output: Source
        :param q_grid_import_output: The q_grid_import_output of this GridOutput.  # noqa: E501
        :type q_grid_import_output: Source
        """
        self.swagger_types = {
            'p_grid_export_output': Source,
            'q_grid_export_output': Source,
            'p_grid_import_output': Source,
            'q_grid_import_output': Source
        }

        self.attribute_map = {
            'p_grid_export_output': 'P_Grid_Export_Output',
            'q_grid_export_output': 'Q_Grid_Export_Output',
            'p_grid_import_output': 'P_Grid_Import_Output',
            'q_grid_import_output': 'Q_Grid_Import_Output'
        }

        self._p_grid_export_output = p_grid_export_output
        self._q_grid_export_output = q_grid_export_output
        self._p_grid_import_output = p_grid_import_output
        self._q_grid_import_output = q_grid_import_output

    @classmethod
    def from_dict(cls, dikt) -> 'GridOutput':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The grid_Output of this GridOutput.  # noqa: E501
        :rtype: GridOutput
        """
        return util.deserialize_model(dikt, cls)

    @property
    def p_grid_export_output(self) -> Source:
        """Gets the p_grid_export_output of this GridOutput.


        :return: The p_grid_export_output of this GridOutput.
        :rtype: Source
        """
        return self._p_grid_export_output

    @p_grid_export_output.setter
    def p_grid_export_output(self, p_grid_export_output: Source):
        """Sets the p_grid_export_output of this GridOutput.


        :param p_grid_export_output: The p_grid_export_output of this GridOutput.
        :type p_grid_export_output: Source
        """
        if p_grid_export_output is None:
            raise ValueError("Invalid value for `p_grid_export_output`, must not be `None`")  # noqa: E501

        self._p_grid_export_output = p_grid_export_output

    @property
    def q_grid_export_output(self) -> Source:
        """Gets the q_grid_export_output of this GridOutput.


        :return: The q_grid_export_output of this GridOutput.
        :rtype: Source
        """
        return self._q_grid_export_output

    @q_grid_export_output.setter
    def q_grid_export_output(self, q_grid_export_output: Source):
        """Sets the q_grid_export_output of this GridOutput.


        :param q_grid_export_output: The q_grid_export_output of this GridOutput.
        :type q_grid_export_output: Source
        """

        self._q_grid_export_output = q_grid_export_output

    @property
    def p_grid_import_output(self) -> Source:
        """Gets the p_grid_import_output of this GridOutput.


        :return: The p_grid_import_output of this GridOutput.
        :rtype: Source
        """
        return self._p_grid_import_output

    @p_grid_import_output.setter
    def p_grid_import_output(self, p_grid_import_output: Source):
        """Sets the p_grid_import_output of this GridOutput.


        :param p_grid_import_output: The p_grid_import_output of this GridOutput.
        :type p_grid_import_output: Source
        """

        self._p_grid_import_output = p_grid_import_output

    @property
    def q_grid_import_output(self) -> Source:
        """Gets the q_grid_import_output of this GridOutput.


        :return: The q_grid_import_output of this GridOutput.
        :rtype: Source
        """
        return self._q_grid_import_output

    @q_grid_import_output.setter
    def q_grid_import_output(self, q_grid_import_output: Source):
        """Sets the q_grid_import_output of this GridOutput.


        :param q_grid_import_output: The q_grid_import_output of this GridOutput.
        :type q_grid_import_output: Source
        """

        self._q_grid_import_output = q_grid_import_output
