# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.meta_load import MetaLoad  # noqa: F401,E501
from swagger_server import util


class LoadFile(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, p_load: List[float]=None, q_load: List[float]=None, meta: MetaLoad=None):  # noqa: E501
        """LoadFile - a model defined in Swagger

        :param p_load: The p_load of this LoadFile.  # noqa: E501
        :type p_load: List[float]
        :param q_load: The q_load of this LoadFile.  # noqa: E501
        :type q_load: List[float]
        :param meta: The meta of this LoadFile.  # noqa: E501
        :type meta: MetaLoad
        """
        self.swagger_types = {
            'p_load': List[float],
            'q_load': List[float],
            'meta': MetaLoad
        }

        self.attribute_map = {
            'p_load': 'P_Load',
            'q_load': 'Q_Load',
            'meta': 'meta'
        }

        self._p_load = p_load
        self._q_load = q_load
        self._meta = meta

    @classmethod
    def from_dict(cls, dikt) -> 'LoadFile':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Load_File of this LoadFile.  # noqa: E501
        :rtype: LoadFile
        """
        return util.deserialize_model(dikt, cls)

    @property
    def p_load(self) -> List[float]:
        """Gets the p_load of this LoadFile.


        :return: The p_load of this LoadFile.
        :rtype: List[float]
        """
        return self._p_load

    @p_load.setter
    def p_load(self, p_load: List[float]):
        """Sets the p_load of this LoadFile.


        :param p_load: The p_load of this LoadFile.
        :type p_load: List[float]
        """
        if p_load is None:
            raise ValueError("Invalid value for `p_load`, must not be `None`")  # noqa: E501

        self._p_load = p_load

    @property
    def q_load(self) -> List[float]:
        """Gets the q_load of this LoadFile.


        :return: The q_load of this LoadFile.
        :rtype: List[float]
        """
        return self._q_load

    @q_load.setter
    def q_load(self, q_load: List[float]):
        """Sets the q_load of this LoadFile.


        :param q_load: The q_load of this LoadFile.
        :type q_load: List[float]
        """

        self._q_load = q_load

    @property
    def meta(self) -> MetaLoad:
        """Gets the meta of this LoadFile.


        :return: The meta of this LoadFile.
        :rtype: MetaLoad
        """
        return self._meta

    @meta.setter
    def meta(self, meta: MetaLoad):
        """Sets the meta of this LoadFile.


        :param meta: The meta of this LoadFile.
        :type meta: MetaLoad
        """

        self._meta = meta
