# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.meta_load import MetaLoad  # noqa: F401,E501
from swagger_server.models.source import Source  # noqa: F401,E501
from swagger_server import util


class Load(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, p_load: Source=None, p_load_r: Source=None, p_load_s: Source=None, p_load_t: Source=None, q_load: Source=None, q_load_r: Source=None, q_load_s: Source=None, q_load_t: Source=None, meta: MetaLoad=None):  # noqa: E501
        """Load - a model defined in Swagger

        :param p_load: The p_load of this Load.  # noqa: E501
        :type p_load: Source
        :param p_load_r: The p_load_r of this Load.  # noqa: E501
        :type p_load_r: Source
        :param p_load_s: The p_load_s of this Load.  # noqa: E501
        :type p_load_s: Source
        :param p_load_t: The p_load_t of this Load.  # noqa: E501
        :type p_load_t: Source
        :param q_load: The q_load of this Load.  # noqa: E501
        :type q_load: Source
        :param q_load_r: The q_load_r of this Load.  # noqa: E501
        :type q_load_r: Source
        :param q_load_s: The q_load_s of this Load.  # noqa: E501
        :type q_load_s: Source
        :param q_load_t: The q_load_t of this Load.  # noqa: E501
        :type q_load_t: Source
        :param meta: The meta of this Load.  # noqa: E501
        :type meta: MetaLoad
        """
        self.swagger_types = {
            'p_load': Source,
            'p_load_r': Source,
            'p_load_s': Source,
            'p_load_t': Source,
            'q_load': Source,
            'q_load_r': Source,
            'q_load_s': Source,
            'q_load_t': Source,
            'meta': MetaLoad
        }

        self.attribute_map = {
            'p_load': 'P_Load',
            'p_load_r': 'P_Load_R',
            'p_load_s': 'P_Load_S',
            'p_load_t': 'P_Load_T',
            'q_load': 'Q_Load',
            'q_load_r': 'Q_Load_R',
            'q_load_s': 'Q_Load_S',
            'q_load_t': 'Q_Load_T',
            'meta': 'meta'
        }

        self._p_load = p_load
        self._p_load_r = p_load_r
        self._p_load_s = p_load_s
        self._p_load_t = p_load_t
        self._q_load = q_load
        self._q_load_r = q_load_r
        self._q_load_s = q_load_s
        self._q_load_t = q_load_t
        self._meta = meta

    @classmethod
    def from_dict(cls, dikt) -> 'Load':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Load of this Load.  # noqa: E501
        :rtype: Load
        """
        return util.deserialize_model(dikt, cls)

    @property
    def p_load(self) -> Source:
        """Gets the p_load of this Load.


        :return: The p_load of this Load.
        :rtype: Source
        """
        return self._p_load

    @p_load.setter
    def p_load(self, p_load: Source):
        """Sets the p_load of this Load.


        :param p_load: The p_load of this Load.
        :type p_load: Source
        """

        self._p_load = p_load

    @property
    def p_load_r(self) -> Source:
        """Gets the p_load_r of this Load.


        :return: The p_load_r of this Load.
        :rtype: Source
        """
        return self._p_load_r

    @p_load_r.setter
    def p_load_r(self, p_load_r: Source):
        """Sets the p_load_r of this Load.


        :param p_load_r: The p_load_r of this Load.
        :type p_load_r: Source
        """

        self._p_load_r = p_load_r

    @property
    def p_load_s(self) -> Source:
        """Gets the p_load_s of this Load.


        :return: The p_load_s of this Load.
        :rtype: Source
        """
        return self._p_load_s

    @p_load_s.setter
    def p_load_s(self, p_load_s: Source):
        """Sets the p_load_s of this Load.


        :param p_load_s: The p_load_s of this Load.
        :type p_load_s: Source
        """

        self._p_load_s = p_load_s

    @property
    def p_load_t(self) -> Source:
        """Gets the p_load_t of this Load.


        :return: The p_load_t of this Load.
        :rtype: Source
        """
        return self._p_load_t

    @p_load_t.setter
    def p_load_t(self, p_load_t: Source):
        """Sets the p_load_t of this Load.


        :param p_load_t: The p_load_t of this Load.
        :type p_load_t: Source
        """

        self._p_load_t = p_load_t

    @property
    def q_load(self) -> Source:
        """Gets the q_load of this Load.


        :return: The q_load of this Load.
        :rtype: Source
        """
        return self._q_load

    @q_load.setter
    def q_load(self, q_load: Source):
        """Sets the q_load of this Load.


        :param q_load: The q_load of this Load.
        :type q_load: Source
        """

        self._q_load = q_load

    @property
    def q_load_r(self) -> Source:
        """Gets the q_load_r of this Load.


        :return: The q_load_r of this Load.
        :rtype: Source
        """
        return self._q_load_r

    @q_load_r.setter
    def q_load_r(self, q_load_r: Source):
        """Sets the q_load_r of this Load.


        :param q_load_r: The q_load_r of this Load.
        :type q_load_r: Source
        """

        self._q_load_r = q_load_r

    @property
    def q_load_s(self) -> Source:
        """Gets the q_load_s of this Load.


        :return: The q_load_s of this Load.
        :rtype: Source
        """
        return self._q_load_s

    @q_load_s.setter
    def q_load_s(self, q_load_s: Source):
        """Sets the q_load_s of this Load.


        :param q_load_s: The q_load_s of this Load.
        :type q_load_s: Source
        """

        self._q_load_s = q_load_s

    @property
    def q_load_t(self) -> Source:
        """Gets the q_load_t of this Load.


        :return: The q_load_t of this Load.
        :rtype: Source
        """
        return self._q_load_t

    @q_load_t.setter
    def q_load_t(self, q_load_t: Source):
        """Sets the q_load_t of this Load.


        :param q_load_t: The q_load_t of this Load.
        :type q_load_t: Source
        """

        self._q_load_t = q_load_t

    @property
    def meta(self) -> MetaLoad:
        """Gets the meta of this Load.


        :return: The meta of this Load.
        :rtype: MetaLoad
        """
        return self._meta

    @meta.setter
    def meta(self, meta: MetaLoad):
        """Sets the meta of this Load.


        :param meta: The meta of this Load.
        :type meta: MetaLoad
        """

        self._meta = meta
