# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class MetaLoad(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, pf_load: float=None):  # noqa: E501
        """MetaLoad - a model defined in Swagger

        :param pf_load: The pf_load of this MetaLoad.  # noqa: E501
        :type pf_load: float
        """
        self.swagger_types = {
            'pf_load': float
        }

        self.attribute_map = {
            'pf_load': 'pf_Load'
        }

        self._pf_load = pf_load

    @classmethod
    def from_dict(cls, dikt) -> 'MetaLoad':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The metaLoad of this MetaLoad.  # noqa: E501
        :rtype: MetaLoad
        """
        return util.deserialize_model(dikt, cls)

    @property
    def pf_load(self) -> float:
        """Gets the pf_load of this MetaLoad.


        :return: The pf_load of this MetaLoad.
        :rtype: float
        """
        return self._pf_load

    @pf_load.setter
    def pf_load(self, pf_load: float):
        """Sets the pf_load of this MetaLoad.


        :param pf_load: The pf_load of this MetaLoad.
        :type pf_load: float
        """
        if pf_load is not None and pf_load > 1:  # noqa: E501
            raise ValueError("Invalid value for `pf_load`, must be a value less than or equal to `1`")  # noqa: E501
        if pf_load is not None and pf_load < 0:  # noqa: E501
            raise ValueError("Invalid value for `pf_load`, must be a value greater than or equal to `0`")  # noqa: E501

        self._pf_load = pf_load
