# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ModelOutput(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, name: str=None, solver: str=None):  # noqa: E501
        """ModelOutput - a model defined in Swagger

        :param name: The name of this ModelOutput.  # noqa: E501
        :type name: str
        :param solver: The solver of this ModelOutput.  # noqa: E501
        :type solver: str
        """
        self.swagger_types = {
            'name': str,
            'solver': str
        }

        self.attribute_map = {
            'name': 'name',
            'solver': 'solver'
        }

        self._name = name
        self._solver = solver

    @classmethod
    def from_dict(cls, dikt) -> 'ModelOutput':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Model_Output of this ModelOutput.  # noqa: E501
        :rtype: ModelOutput
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this ModelOutput.


        :return: The name of this ModelOutput.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this ModelOutput.


        :param name: The name of this ModelOutput.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def solver(self) -> str:
        """Gets the solver of this ModelOutput.


        :return: The solver of this ModelOutput.
        :rtype: str
        """
        return self._solver

    @solver.setter
    def solver(self, solver: str):
        """Sets the solver of this ModelOutput.


        :param solver: The solver of this ModelOutput.
        :type solver: str
        """

        self._solver = solver
