# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ModelUrl(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, up_model_url: str=None):  # noqa: E501
        """ModelUrl - a model defined in Swagger

        :param up_model_url: The up_model_url of this ModelUrl.  # noqa: E501
        :type up_model_url: str
        """
        self.swagger_types = {
            'up_model_url': str
        }

        self.attribute_map = {
            'up_model_url': 'upModelUrl'
        }

        self._up_model_url = up_model_url

    @classmethod
    def from_dict(cls, dikt) -> 'ModelUrl':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Model_url of this ModelUrl.  # noqa: E501
        :rtype: ModelUrl
        """
        return util.deserialize_model(dikt, cls)

    @property
    def up_model_url(self) -> str:
        """Gets the up_model_url of this ModelUrl.


        :return: The up_model_url of this ModelUrl.
        :rtype: str
        """
        return self._up_model_url

    @up_model_url.setter
    def up_model_url(self, up_model_url: str):
        """Sets the up_model_url of this ModelUrl.


        :param up_model_url: The up_model_url of this ModelUrl.
        :type up_model_url: str
        """
        if up_model_url is None:
            raise ValueError("Invalid value for `up_model_url`, must not be `None`")  # noqa: E501

        self._up_model_url = up_model_url
