# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.model_output import ModelOutput  # noqa: F401,E501
from swagger_server import util


class ModelAnswer(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, models: List[ModelOutput]=None):  # noqa: E501
        """ModelAnswer - a model defined in Swagger

        :param models: The models of this ModelAnswer.  # noqa: E501
        :type models: List[ModelOutput]
        """
        self.swagger_types = {
            'models': List[ModelOutput]
        }

        self.attribute_map = {
            'models': 'models'
        }

        self._models = models

    @classmethod
    def from_dict(cls, dikt) -> 'ModelAnswer':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Model_answer of this ModelAnswer.  # noqa: E501
        :rtype: ModelAnswer
        """
        return util.deserialize_model(dikt, cls)

    @property
    def models(self) -> List[ModelOutput]:
        """Gets the models of this ModelAnswer.


        :return: The models of this ModelAnswer.
        :rtype: List[ModelOutput]
        """
        return self._models

    @models.setter
    def models(self, models: List[ModelOutput]):
        """Sets the models of this ModelAnswer.


        :param models: The models of this ModelAnswer.
        :type models: List[ModelOutput]
        """

        self._models = models
