# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class MQTT(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, url: str=None, topic: str=None, qos: int=None):  # noqa: E501
        """MQTT - a model defined in Swagger

        :param url: The url of this MQTT.  # noqa: E501
        :type url: str
        :param topic: The topic of this MQTT.  # noqa: E501
        :type topic: str
        :param qos: The qos of this MQTT.  # noqa: E501
        :type qos: int
        """
        self.swagger_types = {
            'url': str,
            'topic': str,
            'qos': int
        }

        self.attribute_map = {
            'url': 'url',
            'topic': 'topic',
            'qos': 'qos'
        }

        self._url = url
        self._topic = topic
        self._qos = qos

    @classmethod
    def from_dict(cls, dikt) -> 'MQTT':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MQTT of this MQTT.  # noqa: E501
        :rtype: MQTT
        """
        return util.deserialize_model(dikt, cls)

    @property
    def url(self) -> str:
        """Gets the url of this MQTT.


        :return: The url of this MQTT.
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url: str):
        """Sets the url of this MQTT.


        :param url: The url of this MQTT.
        :type url: str
        """

        self._url = url

    @property
    def topic(self) -> str:
        """Gets the topic of this MQTT.


        :return: The topic of this MQTT.
        :rtype: str
        """
        return self._topic

    @topic.setter
    def topic(self, topic: str):
        """Sets the topic of this MQTT.


        :param topic: The topic of this MQTT.
        :type topic: str
        """

        self._topic = topic

    @property
    def qos(self) -> int:
        """Gets the qos of this MQTT.


        :return: The qos of this MQTT.
        :rtype: int
        """
        return self._qos

    @qos.setter
    def qos(self, qos: int):
        """Sets the qos of this MQTT.


        :param qos: The qos of this MQTT.
        :type qos: int
        """

        self._qos = qos
