# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.meta_pv import MetaPV  # noqa: F401,E501
from swagger_server.models.source import Source  # noqa: F401,E501
from swagger_server import util


class PV(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, forecast: bool=None, p_pv: Source=None, meta: MetaPV=None):  # noqa: E501
        """PV - a model defined in Swagger

        :param forecast: The forecast of this PV.  # noqa: E501
        :type forecast: bool
        :param p_pv: The p_pv of this PV.  # noqa: E501
        :type p_pv: Source
        :param meta: The meta of this PV.  # noqa: E501
        :type meta: MetaPV
        """
        self.swagger_types = {
            'forecast': bool,
            'p_pv': Source,
            'meta': MetaPV
        }

        self.attribute_map = {
            'forecast': 'Forecast',
            'p_pv': 'P_PV',
            'meta': 'meta'
        }

        self._forecast = forecast
        self._p_pv = p_pv
        self._meta = meta

    @classmethod
    def from_dict(cls, dikt) -> 'PV':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PV of this PV.  # noqa: E501
        :rtype: PV
        """
        return util.deserialize_model(dikt, cls)

    @property
    def forecast(self) -> bool:
        """Gets the forecast of this PV.

        Is it forecasted data? Or row data  # noqa: E501

        :return: The forecast of this PV.
        :rtype: bool
        """
        return self._forecast

    @forecast.setter
    def forecast(self, forecast: bool):
        """Sets the forecast of this PV.

        Is it forecasted data? Or row data  # noqa: E501

        :param forecast: The forecast of this PV.
        :type forecast: bool
        """
        if forecast is None:
            raise ValueError("Invalid value for `forecast`, must not be `None`")  # noqa: E501

        self._forecast = forecast

    @property
    def p_pv(self) -> Source:
        """Gets the p_pv of this PV.


        :return: The p_pv of this PV.
        :rtype: Source
        """
        return self._p_pv

    @p_pv.setter
    def p_pv(self, p_pv: Source):
        """Sets the p_pv of this PV.


        :param p_pv: The p_pv of this PV.
        :type p_pv: Source
        """
        if p_pv is None:
            raise ValueError("Invalid value for `p_pv`, must not be `None`")  # noqa: E501

        self._p_pv = p_pv

    @property
    def meta(self) -> MetaPV:
        """Gets the meta of this PV.


        :return: The meta of this PV.
        :rtype: MetaPV
        """
        return self._meta

    @meta.setter
    def meta(self, meta: MetaPV):
        """Sets the meta of this PV.


        :param meta: The meta of this PV.
        :type meta: MetaPV
        """

        self._meta = meta
