# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.source import Source  # noqa: F401,E501
from swagger_server import util


class PVOutput(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, p_pv_output: Source=None, q_pv_output: Source=None):  # noqa: E501
        """PVOutput - a model defined in Swagger

        :param p_pv_output: The p_pv_output of this PVOutput.  # noqa: E501
        :type p_pv_output: Source
        :param q_pv_output: The q_pv_output of this PVOutput.  # noqa: E501
        :type q_pv_output: Source
        """
        self.swagger_types = {
            'p_pv_output': Source,
            'q_pv_output': Source
        }

        self.attribute_map = {
            'p_pv_output': 'P_PV_Output',
            'q_pv_output': 'Q_PV_Output'
        }

        self._p_pv_output = p_pv_output
        self._q_pv_output = q_pv_output

    @classmethod
    def from_dict(cls, dikt) -> 'PVOutput':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PV_Output of this PVOutput.  # noqa: E501
        :rtype: PVOutput
        """
        return util.deserialize_model(dikt, cls)

    @property
    def p_pv_output(self) -> Source:
        """Gets the p_pv_output of this PVOutput.


        :return: The p_pv_output of this PVOutput.
        :rtype: Source
        """
        return self._p_pv_output

    @p_pv_output.setter
    def p_pv_output(self, p_pv_output: Source):
        """Sets the p_pv_output of this PVOutput.


        :param p_pv_output: The p_pv_output of this PVOutput.
        :type p_pv_output: Source
        """
        if p_pv_output is None:
            raise ValueError("Invalid value for `p_pv_output`, must not be `None`")  # noqa: E501

        self._p_pv_output = p_pv_output

    @property
    def q_pv_output(self) -> Source:
        """Gets the q_pv_output of this PVOutput.


        :return: The q_pv_output of this PVOutput.
        :rtype: Source
        """
        return self._q_pv_output

    @q_pv_output.setter
    def q_pv_output(self, q_pv_output: Source):
        """Sets the q_pv_output of this PVOutput.


        :param q_pv_output: The q_pv_output of this PVOutput.
        :type q_pv_output: Source
        """

        self._q_pv_output = q_pv_output
