# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.mqtt import MQTT  # noqa: F401,E501
from swagger_server import util


class Source(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, file: bool=None, mqtt: MQTT=None):  # noqa: E501
        """Source - a model defined in Swagger

        :param file: The file of this Source.  # noqa: E501
        :type file: bool
        :param mqtt: The mqtt of this Source.  # noqa: E501
        :type mqtt: MQTT
        """
        self.swagger_types = {
            'file': bool,
            'mqtt': MQTT
        }

        self.attribute_map = {
            'file': 'file',
            'mqtt': 'mqtt'
        }

        self._file = file
        self._mqtt = mqtt

    @classmethod
    def from_dict(cls, dikt) -> 'Source':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Source of this Source.  # noqa: E501
        :rtype: Source
        """
        return util.deserialize_model(dikt, cls)

    @property
    def file(self) -> bool:
        """Gets the file of this Source.


        :return: The file of this Source.
        :rtype: bool
        """
        return self._file

    @file.setter
    def file(self, file: bool):
        """Sets the file of this Source.


        :param file: The file of this Source.
        :type file: bool
        """

        self._file = file

    @property
    def mqtt(self) -> MQTT:
        """Gets the mqtt of this Source.


        :return: The mqtt of this Source.
        :rtype: MQTT
        """
        return self._mqtt

    @mqtt.setter
    def mqtt(self, mqtt: MQTT):
        """Sets the mqtt of this Source.


        :param mqtt: The mqtt of this Source.
        :type mqtt: MQTT
        """

        self._mqtt = mqtt
