# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SourceESSFile(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, value_percent: int=None):  # noqa: E501
        """SourceESSFile - a model defined in Swagger

        :param value_percent: The value_percent of this SourceESSFile.  # noqa: E501
        :type value_percent: int
        """
        self.swagger_types = {
            'value_percent': int
        }

        self.attribute_map = {
            'value_percent': 'value_percent'
        }

        self._value_percent = value_percent

    @classmethod
    def from_dict(cls, dikt) -> 'SourceESSFile':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SourceESSFile of this SourceESSFile.  # noqa: E501
        :rtype: SourceESSFile
        """
        return util.deserialize_model(dikt, cls)

    @property
    def value_percent(self) -> int:
        """Gets the value_percent of this SourceESSFile.


        :return: The value_percent of this SourceESSFile.
        :rtype: int
        """
        return self._value_percent

    @value_percent.setter
    def value_percent(self, value_percent: int):
        """Sets the value_percent of this SourceESSFile.


        :param value_percent: The value_percent of this SourceESSFile.
        :type value_percent: int
        """
        if value_percent is not None and value_percent > 100:  # noqa: E501
            raise ValueError("Invalid value for `value_percent`, must be a value less than or equal to `100`")  # noqa: E501
        if value_percent is not None and value_percent < 0:  # noqa: E501
            raise ValueError("Invalid value for `value_percent`, must be a value greater than or equal to `0`")  # noqa: E501

        self._value_percent = value_percent
