# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.status import Status  # noqa: F401,E501
from swagger_server import util


class StatusOutput(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, status: Dict[str, Status]=None):  # noqa: E501
        """StatusOutput - a model defined in Swagger

        :param status: The status of this StatusOutput.  # noqa: E501
        :type status: Dict[str, Status]
        """
        self.swagger_types = {
            'status': Dict[str, Status]
        }

        self.attribute_map = {
            'status': 'status'
        }

        self._status = status

    @classmethod
    def from_dict(cls, dikt) -> 'StatusOutput':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The StatusOutput of this StatusOutput.  # noqa: E501
        :rtype: StatusOutput
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self) -> Dict[str, Status]:
        """Gets the status of this StatusOutput.


        :return: The status of this StatusOutput.
        :rtype: Dict[str, Status]
        """
        return self._status

    @status.setter
    def status(self, status: Dict[str, Status]):
        """Sets the status of this StatusOutput.


        :param status: The status of this StatusOutput.
        :type status: Dict[str, Status]
        """

        self._status = status
