# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.start import Start  # noqa: F401,E501
from swagger_server import util


class Status(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, config: Start=None, status: str=None, start_time: float=None):  # noqa: E501
        """Status - a model defined in Swagger

        :param config: The config of this Status.  # noqa: E501
        :type config: Start
        :param status: The status of this Status.  # noqa: E501
        :type status: str
        :param start_time: The start_time of this Status.  # noqa: E501
        :type start_time: float
        """
        self.swagger_types = {
            'config': Start,
            'status': str,
            'start_time': float
        }

        self.attribute_map = {
            'config': 'config',
            'status': 'status',
            'start_time': 'start_time'
        }

        self._config = config
        self._status = status
        self._start_time = start_time

    @classmethod
    def from_dict(cls, dikt) -> 'Status':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Status of this Status.  # noqa: E501
        :rtype: Status
        """
        return util.deserialize_model(dikt, cls)

    @property
    def config(self) -> Start:
        """Gets the config of this Status.


        :return: The config of this Status.
        :rtype: Start
        """
        return self._config

    @config.setter
    def config(self, config: Start):
        """Sets the config of this Status.


        :param config: The config of this Status.
        :type config: Start
        """

        self._config = config

    @property
    def status(self) -> str:
        """Gets the status of this Status.


        :return: The status of this Status.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this Status.


        :param status: The status of this Status.
        :type status: str
        """

        self._status = status

    @property
    def start_time(self) -> float:
        """Gets the start_time of this Status.


        :return: The start_time of this Status.
        :rtype: float
        """
        return self._start_time

    @start_time.setter
    def start_time(self, start_time: float):
        """Sets the start_time of this Status.


        :param start_time: The start_time of this Status.
        :type start_time: float
        """

        self._start_time = start_time
