# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class UncertainityFilePluggedTime(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, mean: float=None, std: float=None):  # noqa: E501
        """UncertainityFilePluggedTime - a model defined in Swagger

        :param mean: The mean of this UncertainityFilePluggedTime.  # noqa: E501
        :type mean: float
        :param std: The std of this UncertainityFilePluggedTime.  # noqa: E501
        :type std: float
        """
        self.swagger_types = {
            'mean': float,
            'std': float
        }

        self.attribute_map = {
            'mean': 'mean',
            'std': 'std'
        }

        self._mean = mean
        self._std = std

    @classmethod
    def from_dict(cls, dikt) -> 'UncertainityFilePluggedTime':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The uncertainity_File_Plugged_Time of this UncertainityFilePluggedTime.  # noqa: E501
        :rtype: UncertainityFilePluggedTime
        """
        return util.deserialize_model(dikt, cls)

    @property
    def mean(self) -> float:
        """Gets the mean of this UncertainityFilePluggedTime.


        :return: The mean of this UncertainityFilePluggedTime.
        :rtype: float
        """
        return self._mean

    @mean.setter
    def mean(self, mean: float):
        """Sets the mean of this UncertainityFilePluggedTime.


        :param mean: The mean of this UncertainityFilePluggedTime.
        :type mean: float
        """

        self._mean = mean

    @property
    def std(self) -> float:
        """Gets the std of this UncertainityFilePluggedTime.


        :return: The std of this UncertainityFilePluggedTime.
        :rtype: float
        """
        return self._std

    @std.setter
    def std(self, std: float):
        """Sets the std of this UncertainityFilePluggedTime.


        :param std: The std of this UncertainityFilePluggedTime.
        :type std: float
        """

        self._std = std
