# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.uncertainty_file_ess_states import UncertaintyFileESSStates
from swagger_server.models.uncertainty_file_plugged_time import UncertaintyFilePluggedTime
from swagger_server.models.uncertainty_meta import UncertaintyMeta
from swagger_server import util


class UncertaintyFile(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, meta: UncertaintyMeta=None, plugged_time: UncertaintyFilePluggedTime=None, unplugged_time: UncertaintyFilePluggedTime=None, ess_states: UncertaintyFileESSStates=None, vac_states: UncertaintyFileESSStates=None):  # noqa: E501
        """UncertaintyFile - a model defined in Swagger

        :param meta: The meta of this UncertaintyFile.  # noqa: E501
        :type meta: UncertaintyMeta
        :param plugged_time: The plugged_time of this UncertaintyFile.  # noqa: E501
        :type plugged_time: UncertaintyFilePluggedTime
        :param unplugged_time: The unplugged_time of this UncertaintyFile.  # noqa: E501
        :type unplugged_time: UncertaintyFilePluggedTime
        :param ess_states: The ess_states of this UncertaintyFile.  # noqa: E501
        :type ess_states: UncertaintyFileESSStates
        :param vac_states: The vac_states of this UncertaintyFile.  # noqa: E501
        :type vac_states: UncertaintyFileESSStates
        """
        self.swagger_types = {
            'meta': UncertaintyMeta,
            'plugged_time': UncertaintyFilePluggedTime,
            'unplugged_time': UncertaintyFilePluggedTime,
            'ess_states': UncertaintyFileESSStates,
            'vac_states': UncertaintyFileESSStates
        }

        self.attribute_map = {
            'meta': 'meta',
            'plugged_time': 'Plugged_Time',
            'unplugged_time': 'Unplugged_Time',
            'ess_states': 'ESS_States',
            'vac_states': 'VAC_States'
        }

        self._meta = meta
        self._plugged_time = plugged_time
        self._unplugged_time = unplugged_time
        self._ess_states = ess_states
        self._vac_states = vac_states

    @classmethod
    def from_dict(cls, dikt) -> 'UncertaintyFile':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The uncertainty_File of this UncertaintyFile.  # noqa: E501
        :rtype: UncertaintyFile
        """
        return util.deserialize_model(dikt, cls)

    @property
    def meta(self) -> UncertaintyMeta:
        """Gets the meta of this UncertaintyFile.


        :return: The meta of this UncertaintyFile.
        :rtype: UncertaintyMeta
        """
        return self._meta

    @meta.setter
    def meta(self, meta: UncertaintyMeta):
        """Sets the meta of this UncertaintyFile.


        :param meta: The meta of this UncertaintyFile.
        :type meta: UncertaintyMeta
        """

        self._meta = meta

    @property
    def plugged_time(self) -> UncertaintyFilePluggedTime:
        """Gets the plugged_time of this UncertaintyFile.


        :return: The plugged_time of this UncertaintyFile.
        :rtype: UncertaintyFilePluggedTime
        """
        return self._plugged_time

    @plugged_time.setter
    def plugged_time(self, plugged_time: UncertaintyFilePluggedTime):
        """Sets the plugged_time of this UncertaintyFile.


        :param plugged_time: The plugged_time of this UncertaintyFile.
        :type plugged_time: UncertaintyFilePluggedTime
        """

        self._plugged_time = plugged_time

    @property
    def unplugged_time(self) -> UncertaintyFilePluggedTime:
        """Gets the unplugged_time of this UncertaintyFile.


        :return: The unplugged_time of this UncertaintyFile.
        :rtype: UncertaintyFilePluggedTime
        """
        return self._unplugged_time

    @unplugged_time.setter
    def unplugged_time(self, unplugged_time: UncertaintyFilePluggedTime):
        """Sets the unplugged_time of this UncertaintyFile.


        :param unplugged_time: The unplugged_time of this UncertaintyFile.
        :type unplugged_time: UncertaintyFilePluggedTime
        """

        self._unplugged_time = unplugged_time

    @property
    def ess_states(self) -> UncertaintyFileESSStates:
        """Gets the ess_states of this UncertaintyFile.


        :return: The ess_states of this UncertaintyFile.
        :rtype: UncertaintyFileESSStates
        """
        return self._ess_states

    @ess_states.setter
    def ess_states(self, ess_states: UncertaintyFileESSStates):
        """Sets the ess_states of this UncertaintyFile.


        :param ess_states: The ess_states of this UncertaintyFile.
        :type ess_states: UncertaintyFileESSStates
        """

        self._ess_states = ess_states

    @property
    def vac_states(self) -> UncertaintyFileESSStates:
        """Gets the vac_states of this UncertaintyFile.


        :return: The vac_states of this UncertaintyFile.
        :rtype: UncertaintyFileESSStates
        """
        return self._vac_states

    @vac_states.setter
    def vac_states(self, vac_states: UncertaintyFileESSStates):
        """Sets the vac_states of this UncertaintyFile.


        :param vac_states: The vac_states of this UncertaintyFile.
        :type vac_states: UncertaintyFileESSStates
        """

        self._vac_states = vac_states
