# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class UncertainityFileESSStates(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, min: int=None, max: int=None, steps: int=None):  # noqa: E501
        """UncertainityFileESSStates - a model defined in Swagger

        :param min: The min of this UncertainityFileESSStates.  # noqa: E501
        :type min: int
        :param max: The max of this UncertainityFileESSStates.  # noqa: E501
        :type max: int
        :param steps: The steps of this UncertainityFileESSStates.  # noqa: E501
        :type steps: int
        """
        self.swagger_types = {
            'min': int,
            'max': int,
            'steps': int
        }

        self.attribute_map = {
            'min': 'Min',
            'max': 'Max',
            'steps': 'Steps'
        }

        self._min = min
        self._max = max
        self._steps = steps

    @classmethod
    def from_dict(cls, dikt) -> 'UncertainityFileESSStates':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The uncertainity_File_ESS_States of this UncertainityFileESSStates.  # noqa: E501
        :rtype: UncertainityFileESSStates
        """
        return util.deserialize_model(dikt, cls)

    @property
    def min(self) -> int:
        """Gets the min of this UncertainityFileESSStates.


        :return: The min of this UncertainityFileESSStates.
        :rtype: int
        """
        return self._min

    @min.setter
    def min(self, min: int):
        """Sets the min of this UncertainityFileESSStates.


        :param min: The min of this UncertainityFileESSStates.
        :type min: int
        """

        self._min = min

    @property
    def max(self) -> int:
        """Gets the max of this UncertainityFileESSStates.


        :return: The max of this UncertainityFileESSStates.
        :rtype: int
        """
        return self._max

    @max.setter
    def max(self, max: int):
        """Sets the max of this UncertainityFileESSStates.


        :param max: The max of this UncertainityFileESSStates.
        :type max: int
        """

        self._max = max

    @property
    def steps(self) -> int:
        """Gets the steps of this UncertainityFileESSStates.


        :return: The steps of this UncertainityFileESSStates.
        :rtype: int
        """
        return self._steps

    @steps.setter
    def steps(self, steps: int):
        """Sets the steps of this UncertainityFileESSStates.


        :param steps: The steps of this UncertainityFileESSStates.
        :type steps: int
        """

        self._steps = steps
