# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class UncertainityMeta(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, monte_carlo_repetition: int=None):  # noqa: E501
        """UncertainityMeta - a model defined in Swagger

        :param monte_carlo_repetition: The monte_carlo_repetition of this UncertainityMeta.  # noqa: E501
        :type monte_carlo_repetition: int
        """
        self.swagger_types = {
            'monte_carlo_repetition': int
        }

        self.attribute_map = {
            'monte_carlo_repetition': 'monte_carlo_repetition'
        }

        self._monte_carlo_repetition = monte_carlo_repetition

    @classmethod
    def from_dict(cls, dikt) -> 'UncertainityMeta':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The uncertainity_meta of this UncertainityMeta.  # noqa: E501
        :rtype: UncertainityMeta
        """
        return util.deserialize_model(dikt, cls)

    @property
    def monte_carlo_repetition(self) -> int:
        """Gets the monte_carlo_repetition of this UncertainityMeta.


        :return: The monte_carlo_repetition of this UncertainityMeta.
        :rtype: int
        """
        return self._monte_carlo_repetition

    @monte_carlo_repetition.setter
    def monte_carlo_repetition(self, monte_carlo_repetition: int):
        """Sets the monte_carlo_repetition of this UncertainityMeta.


        :param monte_carlo_repetition: The monte_carlo_repetition of this UncertainityMeta.
        :type monte_carlo_repetition: int
        """

        self._monte_carlo_repetition = monte_carlo_repetition
